Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "idakhlaoS" do |server|
    server.vm.hostname = "idakhlaoS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    
    server.vm.provision "shell", path: "/install_server.sh"
    server.vm.provision "shell", inline: <<-SHELL
      kubectl apply -f /vagrant/deployment.yaml
    SHELL
    
  end

end


# si ca marche pas tester
# echo "Attente du démarrage de l'API Kubernetes..."
#       sleep 20
#       sudo k3s kubectl apply -f /vagrant/deployment.yaml
# curl -H "Host: app1.com" 192.168.56.110