Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "idakhlaoS" do |server|
    server.vm.hostname = "idakhlaoS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    
    server.vm.provision "shell", path: "scripts/install_server.sh"
    server.vm.provision "shell", inline: <<-SHELL
      kubectl apply -f /vagrant/deployment.yaml
    SHELL
    
  end

end