Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "idakhlaoS" do |server|
    server.vm.hostname = "idakhlaoS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    server.vm.provision "shell", path: "scripts/install_server.sh"
    end
  end

  config.vm.define "idakhlaoSW" do |agent|
    agent.vm.hostname = "idakhlaoSW"
    agent.vm.network "private_network", ip: "192.168.56.111"
    
    agent.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    server.vm.provision "shell", path: "scripts/install_worker.sh"
    end
  end

  
end

# installer k3s
# token pour lier server/worker
# isnatllation kubectl si k3s l'a pas installe